### ISSUE TITLE
Fileset parsing error in restore file operation

### ISSUE THREAD

**Issue by fleimgruber** [idursun/jjui#173]
Similar to #164 and #92  but this time not in preview command, but in restore command:

```
details   ✗ jj restore -c ylqktonm Copy (1) case_definitions_LV.xlsx
Error: Failed to parse fileset: Syntax error
Caused by:  --> 1:6
  |
1 | Copy (1) case_definitions_LV.xlsx
  |      ^---
  |
  = expected <EOI>, `|`, `&`, or `~`
Hint: See https://jj-vcs.github.io/jj/latest/filesets/ or use `jj help -k filesets` for filesets syntax and how to match file paths.
```

**Comment by idursun** [comment]
Thanks! That should be fixed now.

**Comment by fleimgruber** [comment]
Thanks for the quick fix (and also for absorb and split)!

**Comment by kaiserinn** [comment]
_Edit: I now realize that the fix is not in version 0.8.12, which is why I'm still having the issue. This is my bad._
\
\
~~I seem to still have the same problem in 0.8.12, specifically when splitting:~~

```
 normal    ✗ jj split -r pvqmnzyq src/routes/(app)/+layout.svelte
Error: Failed to parse fileset: Syntax error
Caused by:  --> 1:12
  |
1 | src/routes/(app)/+layout.svelte
  |            ^---
  |
  = expected <EOI>, `|`, `&`, or `~`
Hint: See https://jj-vcs.github.io/jj/latest/filesets/ or use `jj help -k filesets` for filesets syntax and how to match file paths.
```

Quoting from `jj help -k filesets`:
> Many `jj` commands accept fileset expressions as positional arguments. File
names passed to these commands [must be quoted][string-literals] if they contain
whitespace or meta characters.

**Comment by idursun** [comment]
@kaiserinn no worries. I also thought fix was in the latest release 🤦🏿
